server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: orinpakks01@gmail.com
    password: myif hqvx hans gnfc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

inventory:
  alert:
    recipients: orionpakks01@gmail.com,zachary.rguerra@my.trident.edu
    low-stock-check-minutes: 2